apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapa-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      color: blue
  template:
    metadata:
      name: rapa-blue-pod
      labels:
        color: blue
    spec:
      containers:
      - name: rapa-blue-ctn
        image: brian24/rapa:blue
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rapa-green
spec:
  replicas: 3
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      name: rapa-green-pod
      labels:
        color: green
    spec:
      containers:
      - name: rapa-green-ctn
        image: brian24/rapa:green
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rapa-svc
spec:
  externalTrafficPolicy: Local
  ports:
  - name: rapa-port
    port: 8080
    targetPort: 80
    nodePort: 30001
  selector:
    color: green
  type: NodePort
