apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy2
spec:
  replicas: 1
  selector:
    matchLabels:
      page: blog        # 어떤 라벨 부착된 Pod 에게 전달할 것인가?(1)
  template:     # Pod 정의
    metadata:
      name: blog-pod
      labels:
        page: blog      # (1) 과 동일해야 함
    spec:
      containers:
      - name: blog-ctn
        image: brian24/rapa:blog
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc2
spec:
  selector:
    page: blog
  ports:
  - port: 80    # svc 포트

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-blog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: kakao-nginx
  rules:
  - host: www.kakao.pri
    http:
      paths:
      - path: /blog
        pathType: Prefix
        backend:
          service:
            name: blog-svc2
            port:
              number: 80
