apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80 #svc port
      targetPort: 80 #pod port
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cmap-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: indexcm
      imagePullSecrets:
      - name: hubsec
