apiVersion: v1
kind: Pod
metadata: 
  name: cmap-pod 
spec: 
  containers: 
  - name: cmap-ctn 
    image: nginx 
    envFrom: 
    - configMapRef: 
        name: test1-cmap
    - configMapRef: 
        name: test2-cmap
