apiVersion: v1 
kind: Pod 
metadata: 
  name: cmap-pod-vol 
spec: 
  containers: 
  - name: cmap-ctn-vol 
    image: nginx 
    volumeMounts: 
    - name: cmap-volume 
      mountPath: /etc/testcmap
  volumes: 
  -  name: cmap-volume 
     configMap: 
       name: test1-cmap
