apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rollout-nginx 
spec: 
  replicas: 8 
  strategy: 
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 2 
      maxUnavailable: 2
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      labels: 
        app: nginx 
    spec: 
      containers: 
      - name: nginx 
        image: nginx:1.15.12
