apiVersion: v1
kind: ConfigMap
metadata: 
  namespace: metallb-system 
  name: config 
data: 
  config: |  #마지막줄 비어있는 상태로 포함
    address-pools: 
    - name: default
      protocol: layer2  #layer2, bgp(layer3)
      addresses: 
      - 211.183.3.201-211.183.3.229
