# http://www.test.pri/shop -> shop 디플로이가 서비스 한다
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      page: shop        # 어떤 라벨 부착된 Pod 에게 전달할 것인가?(1)
  template:     # Pod 정의
    metadata:
      name: shop-pod
      labels:
        page: shop      # (1) 과 동일해야 함
    spec:
      containers:
      - name: shop-ctn
        image: brian24/rapa:shop
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shop-svc
spec:
  selector:
    page: shop
  ports:
  - port: 80    # svc 포트

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: ingress-web
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx #기본적으로 클러스터에 1개의 ingress가 구성된다. 회사별로 별도의 경로설정을 하고싶다면 ingressclassname을 각기 따로두고 구성하면 회사별로 별도의 ingress 구성이 가능
  rules: 
  - host: www.test.pri 
    http: 
      paths: 
      - path: /shop 
        pathType: Prefix 
        backend: 
          service: 
            name: shop-svc 
            port: 
              number: 80
